package matve.vacancies.repository;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class Database {
    private final String jdbcUrl;
    private final String username;
    private final String password;

    public Database(String jdbcUrl) {
        this(jdbcUrl, "sa", "");
    }

    public Database(String jdbcUrl, String username, String password) {
        this.jdbcUrl = jdbcUrl;
        this.username = username;
        this.password = password;
    }

    public static Database defaultDatabase() {
        createDataDirectory();
        return new Database("jdbc:h2:file:./data/vacancies;DB_CLOSE_DELAY=-1");
    }

    public Connection getConnection() throws SQLException {
        return DriverManager.getConnection(jdbcUrl, username, password);
    }

    public void initialize() {
        try (Connection connection = getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS sources (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        type VARCHAR(50) NOT NULL,
                        url_template VARCHAR(1000) NOT NULL,
                        enabled BOOLEAN NOT NULL,
                        max_pages INT NOT NULL
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS vacancies (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        source_id BIGINT,
                        source_name VARCHAR(255),
                        external_id VARCHAR(255),
                        title VARCHAR(500) NOT NULL,
                        company VARCHAR(255),
                        city VARCHAR(255),
                        salary_min INT,
                        salary_max INT,
                        currency VARCHAR(20),
                        description CLOB,
                        requirements CLOB,
                        employment_type VARCHAR(50),
                        category VARCHAR(100),
                        published_date DATE,
                        url VARCHAR(1000) NOT NULL,
                        active BOOLEAN NOT NULL,
                        content_hash VARCHAR(128),
                        created_at TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP NOT NULL
                    )
                    """);
            statement.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_vacancies_url ON vacancies(url)");
            statement.execute("CREATE INDEX IF NOT EXISTS idx_vacancies_city ON vacancies(city)");
            statement.execute("CREATE INDEX IF NOT EXISTS idx_vacancies_company ON vacancies(company)");
            statement.execute("CREATE INDEX IF NOT EXISTS idx_vacancies_category ON vacancies(category)");
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS alert_rules (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        city VARCHAR(255),
                        company VARCHAR(255),
                        min_salary INT,
                        keyword VARCHAR(255),
                        employment_type VARCHAR(50),
                        enabled BOOLEAN NOT NULL
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS change_events (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        vacancy_id BIGINT,
                        type VARCHAR(50) NOT NULL,
                        message VARCHAR(1000) NOT NULL,
                        created_at TIMESTAMP NOT NULL
                    )
                    """);
        } catch (SQLException e) {
            throw new RepositoryException("Cannot initialize database", e);
        }
    }

    private static void createDataDirectory() {
        try {
            Files.createDirectories(Path.of("data"));
        } catch (Exception e) {
            throw new RepositoryException("Cannot create data directory", e);
        }
    }
}
